sudo: required
services:
        - docker

before_install:
        - docker build -t dockervmahaj/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run dockervmahaj/react-test npm test -- --coverage

after_success:
        - docker build -t dockervmahaj/multi-client ./client
        - docker build -t dockervmahaj/multi-nginx ./nginx
        - docker build -t dockervmahaj/multi-server ./server
        - docker build -t dockervmahaj/multi-worker ./worker
        # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        # Take those images and push them to docker hub
        - docker push dockervmahaj/multi-client
        - docker push dockervmahaj/multi-nginx
        - docker push dockervmahaj/multi-server
        - docker push dockervmahaj/multi-worker

